### ISSUE TITLE
Using logitech USB Camera

### ISSUE THREAD

**Issue by John-Mccarty** [PhysicsX/Gstreamer-on-embedded-devices#1]
first of all thanks for sharing your work.I cant stream video from rpi with usb camera(logitech web cam) to my ubuntu desktop. I get  error when I run this command on ubuntu "gst-launch-1.0 -v rtspsrc location=rtsp://<my pi ip>:8554/test latency=0 buffer-mode=auto ! decodebin ! videoconvert ! autovideosink sync=false

I get this error on pi
pi@raspberrypi:~/gst-rtsp-server-1.10.4/examples $ ./test-launch --gst-debug=3 "(v4l2src device=/dev/video0 bitrate=8000000 awb-mode=tungsten preview=false ! video/x-h264, width=640, height=480, framerate=30/1 ! h264parse ! rtph264pay name=pay0 pt=96 )"
0:00:00.002690590  1747  0x19a0e80 WARN         GST_PERFORMANCE gstbuffer.c:496:_priv_gst_buffer_initialize: No 64-bit atomic int defined for this platform/toolchain!
stream ready at rtsp://127.0.0.1:8554/test
0:00:07.632465148  1747  0x1b4c4f8 ERROR           GST_PIPELINE gst/parse/grammar.y:412:gst_parse_element_set: no property "bitrate" in element "v4l2src0"
0:00:07.632577536  1747  0x1b4c4f8 ERROR           GST_PIPELINE gst/parse/grammar.y:412:gst_parse_element_set: no property "awb-mode" in element "v4l2src0"
0:00:07.632625033  1747  0x1b4c4f8 ERROR           GST_PIPELINE gst/parse/grammar.y:412:gst_parse_element_set: no property "preview" in element "v4l2src0"
0:00:07.717076525  1747  0x1b4c4f8 WARN        rtspmediafactory rtsp-media-factory.c:1427:default_create_element: recoverable parsing error: no property "bitrate" in element "v4l2src0"
0:00:07.765506087  1747 0x74f090f0 FIXME                default gstutils.c:4025:gst_pad_create_stream_id_internal:<appsrc0:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:07.766095320  1747  0x1b4cb90 WARN                 default v4l2-utils.c:189:gst_v4l2_error:<v4l2src0> error: Cannot identify device '/dev/video0'.
0:00:07.766204531  1747  0x1b4cb90 WARN                 default v4l2-utils.c:192:gst_v4l2_error:<v4l2src0> error: system error: No such file or directory
0:00:07.767757347  1747  0x1b4cb90 WARN               rtspmedia rtsp-media.c:2707:start_preroll: failed to preroll pipeline
0:00:07.767828124  1747  0x1b4cb90 WARN               rtspmedia rtsp-media.c:2830:start_prepare: failed to preroll pipeline
0:00:07.767887286  1747  0x1b4c4f8 WARN               rtspmedia rtsp-media.c:2728:wait_preroll: failed to preroll pipeline
0:00:07.767956605  1747  0x1b4c4f8 WARN               rtspmedia rtsp-media.c:3032:gst_rtsp_media_prepare: failed to preroll pipeline
0:00:07.768229920  1747  0x1b4cb90 WARN               rtspmedia rtsp-media.c:2433:default_handle_message: 0x74f38150: got error Cannot identify device '/dev/video0'. (../sys/v4l2/v4l2_calls.c(608): gst_v4l2_open (): /GstPipeline:media-pipeline/GstBin:bin0/GstV4l2Src:v4l2src0:
system error: No such file or directory)
0:00:07.768296531  1747  0x1b4c4f8 ERROR             rtspclient rtsp-client.c:775:find_media: client 0x1ab63f0: can't prepare media
0:00:07.768553493  1747  0x1b4c4f8 ERROR             rtspclient rtsp-client.c:2309:handle_describe_request: client 0x1ab63f0: no media 

I am using ubuntu 18 and rpi3+ gstreamer version is 1.14..5

**Comment by PhysicsX** [comment]
Yes because you are using the usb camera but also try to use awb-mode these properties which are for picamera. I tried with picamera in the tutorial. 
First try to run usb camera in normal window then you can work on rtsp.
Basicaly picamera properties are different then your usb camera( actually it is  v4l2src)
