### ISSUE TITLE
unable to run nvarguscamerasrc

### ISSUE THREAD

**Issue by kennethakiti1** [PhysicsX/Gstreamer-on-embedded-devices#2]
Hi, i  am using a raspberry pi 4b with raspbian bullseye, i tried following the readme instructions, but when i run the commands but when i run 
`gst-inspect1.0 nvarguscamerasrc`

i get the error 

` No such element or plugin 'nvarguscamerasrc'`

any help with that?

**Comment by PhysicsX** [comment]
Hello,
nvarguscamerasrc is for jetson nano not for raspberry pi as it is mentioned in the readme. 
You can use rpicamsrc. If it is not there, you should build it on the rasp.
Like this: (command also exist in the Readme)
gst-launch-1.0 rpicamsrc preview=false ! 'video/x-raw, width=320, height=320, framerate=30/1' ! videoconvert ! ximagesink
